### ISSUE TITLE
Change API to module and use conventions for keys

### ISSUE THREAD

**Issue by squarism** [poblahblahblah/muchsecrets#2]
Convert most of muchsecrets to be "instance-less", that is, like `muchkeys` is where you don't need an initializer to load or create something on boot.  The API would change from:

``` ruby
wow = MuchSecrets::Secret.new(...)
```

To:

``` ruby
MuchSecrets.configure do |config|
  config.option = ...
end
```

This would solve having global variables all over the place.

By convention, use the private key on the filesystem that matches the consul key.

``` ruby
MuchSecrets.fetch_key('path/to/key')
# this would look in ~/.keys (/root/.keys)
# secrets/fulfillment-production-wc1/foo` would be `/root/.keys/fulfillment-production-wc1.pem
```

Add an option to allow a custom private key:

``` ruby
MuchSecrets.fetch_key('path/to/key', private_key: "/root/.keys/custom.pem")
```

**Comment by poblahblahblah** [comment]
Moved to https://github.com/goldstar/muchkeys
